server.port=8445
spring.datasource.url=jdbc:postgresql://192.168.1.38:5432/employee?currentSchema=employee
spring.datasource.username=employee
spring.datasource.password=employee
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=DemoEmployee

# Enable all endpoints
#management.endpoints.web.exposure.include=*
#management.endpoints.health.show-details=always
#management.endpoints.web.base-path=/admin

#spring.datasource.url=${Demo_Employee_URL} 
#jdbc:postgresql://192.168.1.38:5432/employee?currentSchema=employee
#spring.datasource.username=${Demo_Employee_USERNAME}
#employee
#spring.datasource.password=${Demo_Employee_PASSWORD}
#employee